--CONSULTAS DE AGRUPACION
--ESTE TIPO DE CONSULTAS NOS PERMITEN MOSTRAR ALGUN RESUMEN
--SOBRE UN GRUPO DETERMINADO DE LOS DATOS.
--UTILIZAN FUNCIONES DE AGRUPACION PARA CONSEGUIR EL RESUMEN
--LAS FUNCIONES DEBEN TENER ALIAS
--COUNT(*): Cuenta el número de registros, incluyendo nulos
--COUNT(CAMPO): Cuenta el número de registros sin nulos
--SUM(NUMERO): Suma el total de un campo número
--AVG(NUMERO): Recupera la media de un campo numérico
--MAX(CAMPO): Devuelve el máximo valor de un campo
--MIN(CAMPO): Devuelve el mínimo valor de un campo
--MOSTRAR EL NUMERO DE REGISTROS DE LA TABLA DOCTOR
select count(*) as NUMERO_DOCTORES from DOCTOR;
select count(APELLIDO) as NUMERO_DOCTORES from DOCTOR;
--PODEMOS COMBINAR SIN PROBLEMA VARIAS FUNCIONES:
--QUEREMOS EL NUMERO DE DOCTORES Y EL MAXIMO SALARIO
select count(*) as DOCTORES, max(SALARIO) as MAXIMO from DOCTOR;
--LOS DATOS RESULTANTES DE LAS FUNCIONES PODEMOS AGRUPARLOS POR
--ALGUN CAMPO/S DE LA TABLA
--CUANDO QUEREMOS AGRUPAR UTILIZAMOS group by DESPUES DEL from
--TRUCO: DEBEMOS AGRUPAR POR CADA CAMPO QUE NO SEA UNA FUNCION
--MOSTRAR CUANTOS DOCTORES EXISTEN POR CADA ESPECIALIDAD
select count(*) as DOCTORES, ESPECIALIDAD
from DOCTOR
group by ESPECIALIDAD;

--MOSTRAR NUMERO DE PERSONAS Y MAXIMO SALARIO DE LOS EMPLEADOS
--POR CADA DEPARTAMENTO Y OFICIO
select count(*) as PERSONAS, max(SALARIO) as MAXIMO_SALARIO
, DEPT_NO, OFICIO
from EMP
group by DEPT_NO, OFICIO;

--MOSTRAR EL NUMERO DE PERSONAS DE LA PLANTILLA
select count(*) as PERSONAS from PLANTILLA;
--CUANTAS PERSONAS POR CADA TURNO DE LA PLANTILLA
select count(*) as PERSONAS, TURNO
from PLANTILLA
group by TURNO;
--FILTRANDO EN CONSULTAS DE AGRUPACION
--TENEMOS DOS POSIBILIDADES: 
--WHERE: ANTES DEL GROUP BY Y PARA FILTRAR SOBRE LA TABLA
--HAVING: DESPUES DEL GROUP BY y PARA FILTRAR SOBRE EL CONJUNTO
--MOSTRAR CUANTOS EMPLEADOS TENEMOS POR CADA OFICIO 
--QUE COBREN MAS DE 200.000
select count(*) as EMPLEADOS, OFICIO
from EMP
where SALARIO > 200000
group by OFICIO;
--HAVING: DESPUES DEL GROUP BY y PARA FILTRAR SOBRE EL CONJUNTO
--MOSTRAR CUANTOS EMPLEADOS TENEMOS POR CADA OFICIO 
--Y QUE SEAN ANALISTA O VENDEDOR
--PODEMOS DECIDIR CON HAVING O WHERE
select count(*) as EMPLEADOS, OFICIO
from EMP
group by OFICIO
having OFICIO in ('ANALISTA', 'VENDEDOR');
select count(*) as EMPLEADOS, OFICIO
from EMP
where OFICIO in ('ANALISTA', 'VENDEDOR')
group by OFICIO;
--CUANDO NO PODEMOS DECIDIR Y ESTAMOS OBLIGADOS A UTILIZAR HAVING:
--SI QUEREMOS FILTRAR POR UNA FUNCION DE AGRUPACION
--MOSTRAR CUANTOS EMPLEADOS TENEMOS POR CADA OFICIO 
--SOLAMENTE DONDE TENGAMOS 2 O MAS EMPLEADOS DEL MISMO OFICIO
select count(*) as EMPLEADOS, OFICIO
from EMP
group by OFICIO
having count(*) > 2;





















