select * from EMP;
--LA MEJOR PRAXIS ES UTILIZAR EL NOMBRE DE LOS CAMPOS
--CONTROL + ENTER, EJECUTA LA LINEA EN LA QUE ESTEMOS POSICIONADOS
select APELLIDO, OFICIO, SALARIO from EMP;
--ORDENACION DE DATOS, SIEMPRE AL FINAL Y AFECTA AL SELECT
--LA ORDENACION SIEMPRE ES ASCENDENTE (asc)
select * from EMP order by APELLIDO ASC;
--ORDENACION DESCENDENTE DESC
select * from EMP order by APELLIDO DESC;
--ORDENAR POR MAS DE UN CAMPO
select * from EMP order by DEPT_NO, OFICIO;
--FILTRADO DE REGISTROS
--OPERADORES DE COMPARACION
/*
= igual
>= mayor o igual
<= menor o igual
> mayor
< menor
<> distinto
*/
--Oracle, por defecto, diferencia entre mayúsculas y minúsculas en sus textos (string/varchar)
--TODO LO QUE NO SEA UN NUMERO SE ESCRIBE ENTRE COMILLAS SIMPLES '...'
--PARA FILTRAR SE UTILIZA LA PALABRA where Y SE ESCRIBE SOLAMENTE UNA VEZ EN TODA LA CONSULTA
--DESPUES DEL FROM 
--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10
select * from EMP where DEPT_NO=10;
--MOSTRAR TODOS LOS EMPLEADOS CUYO OFICIO SEA DIRECTOR
select * from EMP where OFICIO='DIRECTOR';
--MOSTRAR TODOS LOS EMPLEADOS CUYO OFICIO SEA DIFERENTE A DIRECTOR
select * from EMP where OFICIO != 'DIRECTOR';
select * from EMP where OFICIO <> 'DIRECTOR';










