--TAMAÑO DE LETRA
--COMENTARIOS
/*
MAS DE UNA LINEA DE COMENTARIO
TENDREMOS TODAS NUESTRAS CONSULTAS
*/
--NO DIFERENCIA MAYUSCULAS DE MINUSCULAS EN LAS PALABRAS CLAVE
select * from DEPT;
select DEPT_NO, DNOMBRE, LOC from DEPT;
